<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mvg</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>MVG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mvg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.mvg</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.mvg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(pop|push)\s+(graphic-context|defs|gradient|pattern|clip-path)\b\s*([^\s]+)?</string>
			<key>name</key>
			<string>meta.keyword.control.mvg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.mvg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.mvg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(affine|arc|bezier|border-color|circle|clip-(path|rule|units)|color|decorate|ellipse|fill(-(opacity|rule))?|font(-(family|size|stretch|style|weight))?|gradient-units|gravity|image|interline-spacing|interword-spacing|kerning|line|matte|offset|opacity|path|point|polygon|polyline|rectangle|rotate|roundrectangle|scale|skew(X|Y)|stop-color|stroke(-(antialias|dasharray|dashoffset|linecap|linejoin|miterlimit|opacity|width))?|text(-(antialias|undercolor))?|translate|viewbox)\b</string>
			<key>name</key>
			<string>support.function.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#(.*?)$</string>
			<key>name</key>
			<string>comment.line.mvg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(url)\(\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.url.mvg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.mvg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(\))\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.mvg</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.support.function.mvg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#[^\)]+</string>
					<key>name</key>
					<string>variable.parameter.url.mvg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?\%?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(linear|radial)\b</string>
			<key>name</key>
			<string>support.type.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(point|replace|floodfill|filltoborder|reset)\b</string>
			<key>name</key>
			<string>support.constant.color.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(none|line-through|overline|underline)\b</string>
			<key>name</key>
			<string>support.constant.decorate.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(evenodd|nonzero)\b</string>
			<key>name</key>
			<string>support.constant.fill-rule.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(all|normal|((extra|semi|ultra)-)?(condensed|expanded))\b</string>
			<key>name</key>
			<string>support.constant.font-stretch.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(all|normal|italic|oblique)\b</string>
			<key>name</key>
			<string>support.constant.font-style.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(all|normal|bold|[1-9]00)?)\b</string>
			<key>name</key>
			<string>support.constant.font-weight.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(userSpace(OnUse)?|objectBoundingBox)?)\b</string>
			<key>name</key>
			<string>support.constant.gradient-units.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(North(East|West)?|West|Center|East|South(East|West)?)\b</string>
			<key>name</key>
			<string>support.constant.gravity.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add|change-mask|clear|color-(burn|dodge)|copy-(red|green|blue|magenta|cyan|yellow|black|opacity)|darken|difference|dst(-(atop|in|out|over))?|exclusion|hard-light|lighten|linear-light|minus|multiply|overlay|plus|screen|soft-light|src(-(atop|in|out|over))?|subtract|xor)\b</string>
			<key>name</key>
			<string>support.constant.compose-method.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(point|replace|floodfill|filltoborder|reset)\b</string>
			<key>name</key>
			<string>support.constant.matte.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(butt|round|square)\b</string>
			<key>name</key>
			<string>support.constant.stroke-linecap.mvg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bevel|miter|round)\b</string>
			<key>name</key>
			<string>support.constant.stroke-linejoin.mvg</string>
		</dict>
	</array>
	<key>scope</key>
	<string>source.mvg</string>
	<key>scopeName</key>
	<string>source.mvg</string>
	<key>uuid</key>
	<string>6E97C7FD-1A75-409C-BD7E-EA8C1168E271</string>
</dict>
</plist>
